=== SkyFire/aion_ext/GameServer/data/static_data/pets/pets.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by MESMERiZE (MSM) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
    <xs:element name="pets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pet" type="pet" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="pet">
        <xs:sequence>
            <xs:element name="petfunction" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="type" type="xs:string"/>
                    <xs:attribute name="id" type="xs:int"/>
                    <xs:attribute name="slots" type="xs:int"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="petstats">
                <xs:complexType>
                    <xs:attribute name="reaction"/>
                    <xs:attribute name="run_speed" type="xs:float"/>
                    <xs:attribute name="walk_speed" type="xs:float"/>
                    <xs:attribute name="height" type="xs:float"/>
                    <xs:attribute name="altitude" type="xs:float"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="nameid" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== SkyFire/aion_ext/gameserver/data/static_data/pets/pets.xml
<?xml version="1.0" encoding="UTF-8"?>
<pets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pets.xsd">
	<pet id="900000" name="Siberian Wild Tiger (Purebred)" nameid="1600012" eggid="190000000">
		<petfunction type="food" id="1"/>
		<petfunction type="warehouse" slots="6"/>
		<petfunction type="bag" id="1020000"/>
		<petfunction type="alarm"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900001" name="Siberian Wild Tiger (Companion)" nameid="1600021" eggid="190000001">
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900002" name="Siberian Wild Tiger (Signal)" nameid="1600023" eggid="190000002">
		<petfunction type="warehouse" slots="12"/>
		<petfunction type="bag" id="1020000"/>
		<petfunction type="alarm"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900003" name="Siberian Wild Tiger (Pack)" nameid="1600025" eggid="190000003">
		<petfunction type="warehouse" slots="6"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900004" name="Siberian Wild Tiger (Fortune 1)" nameid="1600027" eggid="190000004">
		<petfunction type="food" id="1"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900005" name="Siberian Wild Tiger (Fortune 2)" nameid="1600029" eggid="190000005">
		<petfunction type="food" id="2"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900006" name="Siberian Wild Tiger (Fortune 3)" nameid="1600031" eggid="190000006">
		<petfunction type="food" id="3"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900007" name="Siberian Wild Tiger (Fortune 4)" nameid="1600033" eggid="190000007">
		<petfunction type="food" id="4"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900008" name="Siberian Wild Tiger (Fortune 5)" nameid="1600035" eggid="190000008">
		<petfunction type="food" id="5"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900009" name="Siberian Wild Tiger (Fortune 6)" nameid="1600037" eggid="190000009"> 
		<petfunction type="food" id="6"/>
		<petfunction type="bag" id="1020000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900010" name="Grassy Drakie" nameid="1600039" eggid="190010000">
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900011" name="Red Eye Larail" nameid="1600041" eggid="190000010">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900012" name="Quick Kirca" nameid="1600043" eggid="190000011">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.8"/>
	</pet>
	<pet id="900013" name="Manic Aukwi" nameid="1600045" eggid="190000012">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900014" name="Rotund Methu" nameid="1600047" eggid="190000013">
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900015" name="Indigo Ribbit" nameid="1600049" eggid="190000014">
		<petfunction type="wing" id="1030001"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.8"/>
	</pet>
	<pet id="900016" name="Striped Elroco" nameid="1600051" eggid="190000015">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.9"/>
	</pet>
	<pet id="900017" name="Fuzzy Elroco" nameid="1600053" eggid="190020000">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.9"/>
	</pet>
	<pet id="900018" name="Sawteeth Rotan" nameid="1600055" eggid="190000016">
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.3"/>
	</pet>
	<pet id="900019" name="Skullabra Krall" nameid="1600057" eggid="190020001">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.4"/>
	</pet>
	<pet id="900020" name="Bottlenose Tion" nameid="1600059" eggid="190020002">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900021" name="Mau Cubling" nameid="1600061" eggid="190020003">
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900022" name="Golden Wuf" nameid="1600063" eggid="190000017">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.4"/>
	</pet>
	<pet id="900023" name="Silver Wuf" nameid="1600065" eggid="190020004">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.4"/>
	</pet>
	<pet id="900024" name="Desert Naeda" nameid="1600067" eggid="190000027">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="2"/>
	</pet>
	<pet id="900025" name="Jumpy Shugo" nameid="1600069" eggid="190020006">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900026" name="Acute Shugo" nameid="1600071" eggid="190020007">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900027" name="Golden Nyanco" nameid="1600073" eggid="190020008">
		<petfunction type="alarm"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1" altitude="1.5"/>
	</pet>
	<pet id="900028" name="Pink Nyanco" nameid="1600075" eggid="190020009">
		<petfunction type="alarm"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1" altitude="1.5"/>
	</pet>
	<pet id="900029" name="Pesky Manduri" nameid="1600077" eggid="190020010">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.5"/>
	</pet>
	<pet id="900030" name="Mischievous Manduri" nameid="1600079" eggid="190020011">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.5"/>
	</pet>
	<pet id="900031" name="Bluehair Steren" nameid="1600081" eggid="190020012">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.2"/>
	</pet>
	<pet id="900032" name="Pinkhair Steren" nameid="1600083" eggid="190020013">
		<petfunction type="alarm"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.2"/>
	</pet>
	<pet id="900033" name="Silvertail Dorion" nameid="1600085" eggid="190000018">
		<petfunction type="warehouse" slots="6"/>
		<petfunction type="bag" id="1020009"/>
		<petfunction type="wing" id="1030001"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900034" name="Goldentail Dorion" nameid="1600087" eggid="190000019">
		<petfunction type="warehouse" slots="6"/>
		<petfunction type="bag" id="1020009"/>
		<petfunction type="wing" id="1030001"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900035" name="Potbelly Inquin" nameid="1600089" eggid="190010001">
		<petfunction type="warehouse" slots="12"/>
		<petfunction type="bag" id="1020010"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.2"/>
	</pet>
	<pet id="900036" name="Cresent Inquin" nameid="1600091" eggid="190020014">
		<petfunction type="warehouse" slots="12"/>
		<petfunction type="bag" id="1020010"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="cowardly" run_speed="6" walk_speed="1.132" height="1.2"/>
	</pet>
	<pet id="900037" name="Bluemane Trico" nameid="1600093" eggid="190020015">
		<petfunction type="warehouse" slots="12"/>
		<petfunction type="bag" id="1020011"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900038" name="Goldmane Trico" nameid="1600095" eggid="190020016">
		<petfunction type="warehouse" slots="12"/>
		<petfunction type="bag" id="1020011"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="0.7"/>
	</pet>
	<pet id="900039" name="Micro MuMu" nameid="1600097" eggid="190020017">
		<petfunction type="warehouse" slots="18"/>
		<petfunction type="bag" id="1020012"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900040" name="Mini MuMu" nameid="1600099" eggid="190020018">
		<petfunction type="warehouse" slots="18"/>
		<petfunction type="bag" id="1020012"/>
		<petfunction type="wing" id="1030000"/>
		<petstats reaction="brave" run_speed="6" walk_speed="1.132" height="1"/>
	</pet>
	<pet id="900041" name="Shugo Lass" nameid="1600103" eggid="190020019">
		<petfunction type="warehouse" slots="24"/>
