=== SkyFire/aion_ext/gameserver/data/static_data/npc_trade_list.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="npc_trade_list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tradelist_template" type="TradelistTemplate"
					minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TradelistTemplate">
		<xs:sequence>
			<xs:element name="tradelist" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:attribute name="id" type="xs:int" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="category" type="xs:int"/>
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="count" type="xs:int" />
		<xs:attribute name="buy_rate" type="xs:float" default="1" />
		<xs:attribute name="sell_price_rate" type="xs:int"/>

		<xs:attribute name="sell_rate" type="xs:float" default="1" />
		<xs:attribute name="type" type="TradeListType" default="KINAH" />
	</xs:complexType>
	
	<xs:simpleType name="TradeListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="KINAH" />
			<xs:enumeration value="ABYSS" />
			<xs:enumeration value="COUPON" />
			<xs:enumeration value="EXTRA" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== SkyFire/aion_ext/GameServer/data/static_data/npc_trade_list.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="../licenses/Aion-Unique.css" title="License Aion-Unique" alternate="no"?>
<npc_trade_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="npc_trade_list.xsd">
	<tradelist_template npc_id="203060" count="4" category="0">
		<tradelist id="129"/>
		<tradelist id="130"/>
		<tradelist id="131"/>
		<tradelist id="450"/>
	</tradelist_template>
	<tradelist_template npc_id="203061" count="1" category="0">
		<tradelist id="133"/>
	</tradelist_template>
	<tradelist_template npc_id="203063" count="2" category="0">
		<tradelist id="127"/>
		<tradelist id="128"/>
	</tradelist_template>
	<tradelist_template npc_id="203080" count="1" category="0">
		<tradelist id="132"/>
	</tradelist_template>
	<tradelist_template npc_id="203081" count="1" category="0">
		<tradelist id="132"/>
	</tradelist_template>
	<tradelist_template npc_id="203082" count="1" category="0">
		<tradelist id="132"/>
	</tradelist_template>
	<tradelist_template npc_id="203087" count="1" category="0">
		<tradelist id="1"/>
	</tradelist_template>
	<tradelist_template npc_id="203088" count="1" category="0">
		<tradelist id="3"/>
	</tradelist_template>
	<tradelist_template npc_id="203089" count="1" category="0">
		<tradelist id="2"/>
	</tradelist_template>
	<tradelist_template npc_id="203090" count="1" category="0">
		<tradelist id="4"/>
	</tradelist_template>
	<tradelist_template npc_id="203094" count="2" category="0">
		<tradelist id="144"/>
		<tradelist id="69"/>
	</tradelist_template>
	<tradelist_template npc_id="203100" count="4" category="0">
		<tradelist id="134"/>
		<tradelist id="135"/>
		<tradelist id="136"/>
		<tradelist id="137"/>
	</tradelist_template>
	<tradelist_template npc_id="203101" count="5" category="0">
		<tradelist id="138"/>
		<tradelist id="139"/>
		<tradelist id="140"/>
		<tradelist id="141"/>
		<tradelist id="451"/>
	</tradelist_template>
	<tradelist_template npc_id="203107" count="2" category="0">
		<tradelist id="395"/>
		<tradelist id="239"/>
	</tradelist_template>
	<tradelist_template npc_id="203108" count="1" category="0">
		<tradelist id="143"/>
	</tradelist_template>
	<tradelist_template npc_id="203130" count="1" category="0">
		<tradelist id="188"/>
	</tradelist_template>
	<tradelist_template npc_id="203131" count="3" category="0">
		<tradelist id="142"/>
		<tradelist id="143"/>
		<tradelist id="239"/>
	</tradelist_template>
	<tradelist_template npc_id="203158" count="2" category="0">
		<tradelist id="142"/>
		<tradelist id="143"/>
	</tradelist_template>
	<tradelist_template npc_id="203161" count="1" category="0">
		<tradelist id="156"/>
	</tradelist_template>
	<tradelist_template npc_id="203179" count="3" category="3">
		<tradelist id="938"/>
		<tradelist id="940"/>
		<tradelist id="942"/>
	</tradelist_template>
	<tradelist_template npc_id="203200" count="1" category="0">
		<tradelist id="240"/>
	</tradelist_template>
	<tradelist_template npc_id="203224" count="1" category="0">
		<tradelist id="241"/>
	</tradelist_template>
	<tradelist_template npc_id="203225" count="1" category="0">
		<tradelist id="242"/>
	</tradelist_template>
	<tradelist_template npc_id="203226" count="1" category="0">
		<tradelist id="331"/>
	</tradelist_template>
	<tradelist_template npc_id="203227" count="1" category="0">
		<tradelist id="332"/>
	</tradelist_template>
	<tradelist_template npc_id="203228" count="1" category="0">
		<tradelist id="333"/>
	</tradelist_template>
	<tradelist_template npc_id="203234" count="3" category="0">
		<tradelist id="119"/>
		<tradelist id="120"/>
		<tradelist id="442"/>
	</tradelist_template>
	<tradelist_template npc_id="203235" count="2" category="0">
		<tradelist id="123"/>
		<tradelist id="125"/>
	</tradelist_template>
	<tradelist_template npc_id="203236" count="3" category="0">
		<tradelist id="121"/>
		<tradelist id="122"/>
		<tradelist id="443"/>
	</tradelist_template>
	<tradelist_template npc_id="203237" count="2" category="0">
		<tradelist id="124"/>
		<tradelist id="126"/>
	</tradelist_template>
	<tradelist_template npc_id="203248" count="2" category="0">
		<tradelist id="94"/>
		<tradelist id="88"/>
	</tradelist_template>
	<tradelist_template npc_id="203249" count="2" category="0">
		<tradelist id="95"/>
		<tradelist id="89"/>
	</tradelist_template>
	<tradelist_template npc_id="203250" count="2" category="0">
		<tradelist id="98"/>
		<tradelist id="92"/>
	</tradelist_template>
	<tradelist_template npc_id="203251" count="2" category="0">
		<tradelist id="97"/>
		<tradelist id="91"/>
	</tradelist_template>
	<tradelist_template npc_id="203252" count="2" category="0">
		<tradelist id="96"/>
		<tradelist id="90"/>
	</tradelist_template>
	<tradelist_template npc_id="203253" count="2" category="0">
		<tradelist id="99"/>
		<tradelist id="93"/>
	</tradelist_template>
	<tradelist_template npc_id="203254" count="1" category="0">
		<tradelist id="245"/>
	</tradelist_template>
	<tradelist_template npc_id="203255" count="2" category="0">
		<tradelist id="246"/>
		<tradelist id="405"/>
	</tradelist_template>
	<tradelist_template npc_id="203256" count="1" category="0">
		<tradelist id="248"/>
	</tradelist_template>
	<tradelist_template npc_id="203257" count="2" category="0">
		<tradelist id="249"/>
		<tradelist id="406"/>
	</tradelist_template>
	<tradelist_template npc_id="203258" count="1" category="0">
		<tradelist id="250"/>
	</tradelist_template>
	<tradelist_template npc_id="203259" count="2" category="0">
		<tradelist id="251"/>
		<tradelist id="407"/>
	</tradelist_template>
	<tradelist_template npc_id="203260" count="1" category="0">
		<tradelist id="252"/>
	</tradelist_template>
	<tradelist_template npc_id="203261" count="2" category="0">
		<tradelist id="253"/>
		<tradelist id="408"/>
	</tradelist_template>
	<tradelist_template npc_id="203262" count="1" category="0">
		<tradelist id="254"/>
	</tradelist_template>
	<tradelist_template npc_id="203263" count="2" category="0">
		<tradelist id="255"/>
		<tradelist id="409"/>
	</tradelist_template>
	<tradelist_template npc_id="203264" count="3" category="0">
		<tradelist id="247"/>
		<tradelist id="258"/>
		<tradelist id="414"/>
	</tradelist_template>
	<tradelist_template npc_id="203265" count="1" category="0">
		<tradelist id="256"/>
	</tradelist_template>
	<tradelist_template npc_id="203266" count="1" category="0">
		<tradelist id="335"/>
	</tradelist_template>
	<tradelist_template npc_id="203267" count="2" category="0">
		<tradelist id="336"/>
		<tradelist id="405"/>
	</tradelist_template>
	<tradelist_template npc_id="203268" count="1" category="0">
		<tradelist id="338"/>
	</tradelist_template>
	<tradelist_template npc_id="203269" count="2" category="0">
		<tradelist id="339"/>
		<tradelist id="410"/>
	</tradelist_template>
	<tradelist_template npc_id="203270" count="1" category="0">
		<tradelist id="340"/>
	</tradelist_template>
	<tradelist_template npc_id="203271" count="2" category="0">
		<tradelist id="341"/>
		<tradelist id="411"/>
	</tradelist_template>
	<tradelist_template npc_id="203272" count="1" category="0">
		<tradelist id="342"/>
	</tradelist_template>
	<tradelist_template npc_id="203273" count="2" category="0">
		<tradelist id="343"/>
		<tradelist id="412"/>
	</tradelist_template>
	<tradelist_template npc_id="203274" count="1" category="0">
		<tradelist id="344"/>
	</tradelist_template>
	<tradelist_template npc_id="203275" count="2" category="0">
		<tradelist id="345"/>
		<tradelist id="413"/>
	</tradelist_template>
	<tradelist_template npc_id="203276" count="3" category="0">
		<tradelist id="337"/>
		<tradelist id="347"/>
		<tradelist id="414"/>
	</tradelist_template>
	<tradelist_template npc_id="203277" count="1" category="0">
		<tradelist id="346"/>
	</tradelist_template>
	<tradelist_template npc_id="203288" count="2" category="0">
		<tradelist id="21"/>
		<tradelist id="599"/>
	</tradelist_template>
	<tradelist_template npc_id="203289" count="2" category="0">
		<tradelist id="22"/>
		<tradelist id="600"/>
	</tradelist_template>
	<tradelist_template npc_id="203290" count="2" category="0">
		<tradelist id="23"/>
		<tradelist id="601"/>
	</tradelist_template>
	<tradelist_template npc_id="203291" count="2" category="0">
		<tradelist id="24"/>
		<tradelist id="602"/>
	</tradelist_template>
	<tradelist_template npc_id="203292" count="2" category="0">
		<tradelist id="27"/>
		<tradelist id="605"/>
	</tradelist_template>
	<tradelist_template npc_id="203293" count="2" category="0">
		<tradelist id="28"/>
		<tradelist id="606"/>
	</tradelist_template>
	<tradelist_template npc_id="203294" count="2" category="0">
		<tradelist id="25"/>
		<tradelist id="603"/>
	</tradelist_template>
	<tradelist_template npc_id="203295" count="2" category="0">
		<tradelist id="26"/>
		<tradelist id="604"/>
	</tradelist_template>
	<tradelist_template npc_id="203296" count="2" category="0">
		<tradelist id="49"/>
		<tradelist id="607"/>
	</tradelist_template>
	<tradelist_template npc_id="203297" count="2" category="0">
		<tradelist id="50"/>
		<tradelist id="608"/>
	</tradelist_template>
	<tradelist_template npc_id="203298" count="2" category="0">
		<tradelist id="51"/>
		<tradelist id="609"/>
	</tradelist_template>
	<tradelist_template npc_id="203299" count="2" category="0">
		<tradelist id="52"/>
		<tradelist id="610"/>
	</tradelist_template>
	<tradelist_template npc_id="203300" count="2" category="0">
		<tradelist id="55"/>
		<tradelist id="613"/>
	</tradelist_template>
	<tradelist_template npc_id="203301" count="2" category="0">
		<tradelist id="56"/>
		<tradelist id="614"/>
	</tradelist_template>
	<tradelist_template npc_id="203302" count="2" category="0">
		<tradelist id="53"/>
		<tradelist id="611"/>
	</tradelist_template>
	<tradelist_template npc_id="203303" count="2" category="0">
		<tradelist id="54"/>
		<tradelist id="612"/>
	</tradelist_template>
	<tradelist_template npc_id="203304" count="4" category="0">
		<tradelist id="86"/>
