=== SkyFire/aion_ext/gameserver/data/static_data/world_maps.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:element name="world_maps">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="map" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence/>
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="id" type="xs:int" use="required"/>
						<xs:attribute name="nameid" type="xs:int" default="0"/>
						<xs:attribute name="twin_count" type="xs:int"/>
						<xs:attribute name="max_user" type="xs:int"/>
						<xs:attribute name="prison" type="xs:boolean"/>
						<xs:attribute name="instance" type="xs:boolean"/>
						<xs:attribute name="instanceMapId" type="xs:int"/>
						<xs:attribute name="cooldown" type="xs:int"/>
						<xs:attribute name="water_level" type="xs:int" use="required"/>
						<xs:attribute name="death_level" type="xs:int" use="required"/>
						<xs:attribute name="world_type" type="worldType"/>
						<xs:attribute name="world_size" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="worldType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ASMODAE"/>
			<xs:enumeration value="ELYSEA"/>
			<xs:enumeration value="BALAUREA"/>
			<xs:enumeration value="ABYSS"/>
			<xs:enumeration value="NONE"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== SkyFire/aion_ext/GameServer/data/static_data/world_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../licenses/Aion-Unique.css" title="License" alternate="no"?>
<world_maps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="world_maps.xsd">
	<map id="110010000" name="Sanctum" death_level="400" water_level="16" world_type="ELYSEA"/>
	<map id="110020000" name="Kaisinel" death_level="0" water_level="16" world_type="ELYSEA"/>
	<map id="120010000" name="Pandaemonium" death_level="150" water_level="16" world_type="ASMODAE"/>
	<map id="120020000" name="Marchutan" death_level="0" water_level="16" world_type="ASMODAE"/>
	<map id="210010000" name="Poeta" max_user="200" twin_count="2" death_level="0" water_level="100" world_type="ELYSEA"/>
	<map id="210020000" name="Eltnen" death_level="0" water_level="6" world_type="ELYSEA"/>
	<map id="210030000" name="Verteron" max_user="200" death_level="0" water_level="100" world_type="ELYSEA"/>
	<map id="210040000" name="Heiron" death_level="0" water_level="100" world_type="ELYSEA"/>
	<map id="210050000" name="Inggison" death_level="0" water_level="16" world_type="BALAUREA"/>
	<map id="210060000" name="Theomobos" death_level="0" water_level="1" world_type="ELYSEA"/>
	<map id="220010000" name="Ishalgen" max_user="200" twin_count="2" death_level="0" water_level="248" world_type="ASMODAE"/>
	<map id="220020000" name="Morheim" death_level="0" water_level="16" world_type="ASMODAE"/>
	<map id="220030000" name="Altgard" max_user="200" death_level="0" water_level="248" world_type="ASMODAE"/>
	<map id="220040000" name="Beluslan" death_level="0" water_level="16" world_type="ASMODAE"/>
	<map id="220050000" name="Brusthonin" death_level="0" water_level="5" world_type="ASMODAE"/>
	<map id="220070000" name="Gelkmaros" death_level="0" water_level="16" world_type="BALAUREA"/>
	<map id="300010000" name="IDAbPro" death_level="0" water_level="16"/>
	<map id="300020000" name="IDTest_Dungeon" death_level="0" water_level="16"/>
	<map id="300030000" name="NochsanaTrainingCamp" instance="true" instanceId="8" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300040000" name="DarkPoeta" instance="true" instanceId="9" cooldown="720" death_level="0" water_level="16"/>
	<map id="300050000" name="AstreiaChamber" instance="true" instanceId="13" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300060000" name="SulfurTreeNest" instance="true" instanceId="10" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300070000" name="ChamberOfRoah" instance="true" instanceId="14" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300080000" name="LeftWingChamber" instance="true" instanceId="12" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300090000" name="RightWingChamber" instance="true" instanceId="11" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300100000" name="SteelRake" instance="true" instanceId="18" cooldown="300" death_level="0" water_level="16"/>
	<map id="300110000" name="Dredgion" instance="true" instanceId="19" cooldown="120" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300120000" name="KysisChamber" instance="true" instanceId="16" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300130000" name="MirenChamber" instance="true" instanceId="17" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300140000" name="KrotanChamber" instance="true" instanceId="15" cooldown="1080" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300150000" name="Udas Temple" instance="true" instanceId="26" cooldown="360" death_level="0" water_level="16"/>
	<map id="300160000" name="Lower Udas Temple" instance="true" instanceId="27" cooldown="360" death_level="0" water_level="16"/>
	<map id="300170000" name="Beshmundir Temple" instance="true" instanceId="28" cooldown="720" death_level="0" water_level="16"/>
	<map id="300190000" name="TalocsHollow" instance="true" instanceId="29" cooldown="2760" death_level="0" water_level="16" world_type="ABYSS"/>
	<map id="300200000" name="Haramel" instance="true" instanceId="46" cooldown="180" death_level="0" water_level="16"/>
	<map id="300210000" name="IDDreadgion_02" instance="true" death_level="0" water_level="16"/>
	<map id="300220000" name="Hidden Cave" instance="true" instanceId="44" cooldown="2760" death_level="0" water_level="16"/>
	<map id="300230000" name="KromedesTrial" instance="true" instanceId="45" cooldown="1320" death_level="0" water_level="16"/>
	<map id="310010000" name="Karamatis" instance="true" instanceId="30" cooldown="0" death_level="0" water_level="16"/>
	<map id="310020000" name="Karamatis" instance="true" instanceId="31" cooldown="0" death_level="0" water_level="16"/>
	<map id="310030000" name="Aerdina" instance="true" instanceId="20" cooldown="0" death_level="0" water_level="16"/>
	<map id="310040000" name="Geranaia" instance="true" instanceId="21" cooldown="0" death_level="0" water_level="16"/>
	<map id="310050000" name="Aetherogenetics_Lab" instance="true" instanceId="4" cooldown="10" death_level="0" water_level="16"/>
	<map id="310060000" name="Sliver of Darkness" instance="true" instanceId="40" cooldown="0" death_level="0" water_level="16"/>
	<map id="310070000" name="Sliver of Darkness_Stigma" instance="true" instanceId="41" cooldown="0" death_level="0" water_level="16"/>
	<map id="310080000" name="Sanctum Underground Arena" death_level="0" water_level="16"/>
	<map id="310090000" name="Indratu Fortress" instance="true" instanceId="42" cooldown="0" death_level="0" water_level="16"/>
	<map id="310100000" name="Azoturan Fortress" instance="true" instanceId="25" cooldown="0" death_level="0" water_level="16"/>
	<map id="310110000" name="TheobomosLab" instance="true" instanceId="6" cooldown="180" death_level="0" water_level="16"/>
	<map id="310120000" name="Ataxiar" instance="true" instanceId="32" cooldown="0" death_level="0" water_level="16"/>
	<map id="320010000" name="Ataxiar" instance="true" instanceId="33" cooldown="0" death_level="0" water_level="16"/>
	<map id="320020000" name="Ataxiar" instance="true" instanceId="34" cooldown="0" death_level="0" water_level="16"/>
	<map id="320030000" name="Bregirun" death_level="0" water_level="16"/>
	<map id="320040000" name="Nidalber" death_level="0" water_level="16"/>
	<map id="320050000" name="Sky Temple Interior" instance="true" instanceId="24" cooldown="0" death_level="0" water_level="16"/>
	<map id="320060000" name="Space of Oblivion" death_level="0" water_level="16"/>
	<map id="320070000" name="Space of Destiny" instance="true" death_level="0" water_level="16"/>
	<map id="320080000" name="Draupnir Cave" instance="true" instanceId="2" cooldown="360" death_level="0" water_level="16"/>
	<map id="320090000" name="Triniel Underground Arena" death_level="0" water_level="16"/>
	<map id="320100000" name="Fire Temple" instance="true" instanceId="3" cooldown="30" death_level="0" water_level="16"/>
	<map id="320110000" name="Alquimia Research Center" instance="true" instanceId="5" cooldown="10" death_level="0" water_level="16"/>
    <map id="320120000" name="Shadow Court Dungeon" instanceId="37" death_level="0" water_level="16"/>
	<map id="320130000" name="AdmaStronghold" instance="true" instanceId="7" cooldown="180" death_level="0" water_level="16"/>
	<map id="320140000" name="IDAbProD3" instance="true" instanceId="35" cooldown="0" death_level="0" water_level="16"/>
	<map id="400010000" name="Reshanta" death_level="500" water_level="16" world_type="ABYSS"/>
	<map id="510010000" prison="true" name="LF_Prison" death_level="0" water_level="16"/>
	<map id="520010000" prison="true" name="DF_Prison" death_level="0" water_level="16"/>
	<map id="600010000" name="Silentera_Canyon" death_level="0" water_level="16" world_type="BALAUREA"/>
	<map id="900020000" twin_count="10" name="Test_Basic" death_level="0" water_level="16"/>
	<map id="900030000" twin_count="5" name="Test_Server" death_level="0" water_level="1"/>
	<map id="900100000" name="Test_GiantMonster" death_level="0" water_level="16"/>
	<map id="900110000" name="Housing_barrack" death_level="0" water_level="16"/>
</world_maps>
